spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:15432/catalogDB
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    git:
      enabled: true
      mode: full

