name: 'biglibrary'
services:
  catalog-service:
    image: 'prasannakumar22/biglibrary-catalog-service:latest'
    ports:
      - '8081:8081'
#    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalogDB:5432/catalogDB
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    restart: unless-stopped
    depends_on:
      catalogDB:
        condition: service_healthy
    deploy:
        resources:
            limits:
              memory: 700m

  order-service:
    image: 'prasannakumar22/biglibrary-order-service:latest'
    ports:
      - '8082:8082'
#    container_name: order-service
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - ORDER_CATALOG_SERVICE_URL=http://catalog-service:8081
        - AUTH_SERVICE_URL=http://auth-service:4000
        - DB_URL=jdbc:postgresql://orderDB:5432/orderDB
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USERNAME=guest
        - RABBITMQ_PASSWORD=guest
    restart: unless-stopped
    depends_on:
      orderDB:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
        resources:
            limits:
              memory: 700m

  notification-service:
    image: 'prasannakumar22/biglibrary-notification-service:latest'
    ports:
      - '8083:8083'
#    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://notificationDB:5432/notificationDB
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    depends_on:
      notificationDB:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m

  auth-service:
    image: 'prasannakumar22/biglibrary-auth-service:latest'
    ports:
      - '4000:4000'
    env_file:
      - .env.deploy
#    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://authDB:5432/authDB
      - DB_USER=postgres
      - DB_PASSWORD=postgres
#      - JWT_SECRET=${JWT_SECRET}
#      - JWT_AUTHORIZATION=Authorization
    restart: unless-stopped
    depends_on:
      authDB:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m


  gateway:
    image: 'prasannakumar22/biglibrary-gateway:latest'
    ports:
      - '8080:8080'
#    container_name: gateway
    env_file:
      - .env.deploy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CATALOG_SERVICE_URL=http://catalog-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082
      - AUTH_SERVICE_URL=http://auth-service:4000
    depends_on:
      catalog-service:
        condition: service_started
      order-service:
        condition: service_started
      auth-service:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
#    networks:
#      - biglibrary-network

#networks:
#  biglibrary-network:
#    external: true



