name: 'big-library'
services:
  catalogDB:
    image: 'postgres:16-alpine'
    container_name: 'catalogDB'
    env_file:
      - .env.deploy
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: 'catalogDB'
    ports:
      - '15432:5432'
    volumes:
      - catalogdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
  orderDB:
    image: 'postgres:16-alpine'
    container_name: 'orderDB'
    env_file:
      - .env.deploy
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: 'orderDB'
    ports:
      - '25432:5432'
    volumes:
      - orderdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
  notificationDB:
    image: 'postgres:16-alpine'
    container_name: 'notificationDB'
    env_file:
      - .env.deploy
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: 'notificationDB'
    ports:
      - '35432:5432'
    volumes:
      - notificationdb_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
  authDB:
    image: 'postgres:16-alpine'
    container_name: 'authDB'
    env_file:
      - .env.deploy
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: 'authDB'
    ports:
      - '45432:5432'
    volumes:
      - authdb_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
  biglibrary-rabbitmq:
    image: rabbitmq:3.12-management
    container_name: 'biglibrary-rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - '15672:15672'
      - '5672:5672'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500m
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0.2
#    command: ['start-dev', '--import-realm', '--http-port=9191']
#    container_name: 'keycloak'
#    hostname: 'keycloak'
#    volumes:
#      - ./realm-config:/opt/keycloak/data/import
#    environment:
#        KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
#        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin1234}
#    ports:
#      - '9191:9191'
#    deploy:
#        resources:
#            limits:
#              memory: 2gb

volumes:
  catalogdb_data:
  orderdb_data:
  notificationdb_data:
  authdb_data:
