spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          globalcors:
            cors-configurations:
                '[/**]':
                    allowedOriginPatterns: "*"
                    allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                    - OPTIONS
                    allowedHeaders: "*"
                    allowCredentials: true
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:4000}
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /auth/${segment}
            - id: catalog-service
              uri: ${CATALOG_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/catalog/**, /api/products/**
              filters:
                - RewritePath=/api/catalog/(?<segment>.*), /api/products/${segment}
            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/orders/**
              filters:
                - RewritePath=/api/orders/(?<segment>.*), /api/orders/${segment}
            - id: catalog-service-docs
              uri: ${CATALOG_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/v3/api-docs/catalog/**
              filters:
                - RewritePath=/v3/api-docs/catalog/?(?<segment>.*), /v3/api-docs${segment}
            - id: order-service-docs
              uri: ${ORDER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/v3/api-docs/order/**
              filters:
                - RewritePath=/v3/api-docs/order/?(?<segment>.*), /v3/api-docs${segment}
            - id: openapi
              uri: http://localhost:${server.port}
              predicates:
                - Path=/v3/api-docs

mvc:
  problemdetails:
    enabled: true

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"


springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    use-root-path: true
    enabled: false

jwt:
  header: ${JWT_HEADER:Authorization}
  secret: ${JWT_SECRET}

